/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import javax.swing.JOptionPane;

/**
 *
 * @author FazalUr
 */
public class PageTwo extends javax.swing.JFrame {

    /**
     * Creates new form PageTwo
     */
    public PageTwo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrator Menu");
        setMaximumSize(new java.awt.Dimension(1000, 630));
        setMinimumSize(new java.awt.Dimension(1000, 630));
        setResizable(false);

        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 630));
        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton1.setText("Log Out");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(820, 20, 170, 40);

        jButton2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton2.setText("Update existing employee");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(10, 520, 240, 60);

        jButton3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton3.setText("Search room");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(860, 550, 130, 30);

        jButton4.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton4.setText("Add new student");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(10, 170, 240, 60);

        jButton5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton5.setText("Delete existing student");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(10, 240, 240, 60);

        jButton6.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton6.setText("Update existing student");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(10, 310, 240, 60);

        jButton7.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton7.setText("Add new employee");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(10, 380, 240, 60);

        jButton8.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton8.setText("Delete existing employee");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(10, 450, 240, 60);

        jButton9.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton9.setText("Calculate bills");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton9);
        jButton9.setBounds(10, 30, 240, 60);

        jButton10.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton10.setText("Search student");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10);
        jButton10.setBounds(580, 550, 130, 30);

        jButton11.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton11.setText("Search employee");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton11);
        jButton11.setBounds(720, 550, 130, 30);

        jButton12.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton12.setText("View total Earnings");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton12);
        jButton12.setBounds(10, 100, 240, 60);

        jButton13.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton13.setText("Delete existing room");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton13);
        jButton13.setBounds(820, 170, 170, 40);

        jButton14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton14.setText("Add new room");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton14);
        jButton14.setBounds(820, 70, 170, 40);

        jButton15.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jButton15.setText("Update existing room");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton15);
        jButton15.setBounds(820, 120, 170, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Main/002.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1, -2, 1000, 630);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(Main.P2, "Logging you out..");
        Main.P2.setVisible(false);
        Main.P1.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        // TODO add your handling code here:
        int A = Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter room id to delete: "));
        if (Main.H1.isSearchRoom(A))
        {
            int Index = Main.H1.searchRoom(A);
            JOptionPane.showMessageDialog(this, "Room found & deleted successfully!");
            for (int i=0;i<Hostel.roomsCounter;i++)
            {
                Main.H1.getR1()[i] = Main.H1.getR1()[i+1];
            }
            Hostel.roomsCounter-=1;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Sorry, no room found!");          
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
        Main.H1.getR1()[Hostel.roomsCounter].setFacilities(JOptionPane.showInputDialog(this, "Enter facilities available in room: "));
        Main.H1.getR1()[Hostel.roomsCounter].setCharges(Double.parseDouble(JOptionPane.showInputDialog(this, "Enter charges for room: ")));
        Main.H1.getR1()[Hostel.roomsCounter].setId(Hostel.roomsCounter+1);
        JOptionPane.showMessageDialog(this, "New room created successfully!");
        Hostel.roomsCounter+=1;
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        // TODO add your handling code here:
        int A = Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter room id to update: "));
        if (Main.H1.isSearchRoom(A))
        {
            int Index = Main.H1.searchRoom(A);
            JOptionPane.showMessageDialog(this, "Room found.");
            Main.H1.getR1()[Index].setCharges(Double.parseDouble(JOptionPane.showInputDialog(this, "Enter charges to update: ")));
            Main.H1.getR1()[Index].setFacilities(JOptionPane.showInputDialog(this, "Enter facilities to update: "));
            Main.H1.getR1()[Index].setStatus(Boolean.valueOf(JOptionPane.showInputDialog(this, "Enter room status i-e true or false: ")));
            JOptionPane.showMessageDialog(this, "Room found & updated successfully!");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Sorry, no room found!");
        }
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int A = Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter room no. to search: "));
        if (Main.H1.isSearchRoom(A))
        {
            JOptionPane.showMessageDialog(Main.P2, "Room found successfully.");
            int Index = Main.H1.searchRoom(A);
            JOptionPane.showMessageDialog(Main.P2, "\n----- Room Statistics ----- \nRoom no: " + Main.H1.getR1()[Index].getId() + "\nFacilities: " + Main.H1.getR1()[Index].getFacilities() + "\nCharges: " + Main.H1.getR1()[Index].getCharges() + "\nEmployee Assigned: " + Main.H1.getE1()[Main.H1.getR1()[Index].getEmployeeAssigned()].getName() + "\nStatus: " + Main.H1.getR1()[Index].isStatus());
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "Sorry! No room found.");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
        int A = Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter employee id to search: "));
        if (Main.H1.isSearchEmployee(A))
        {
            JOptionPane.showMessageDialog(Main.P2, "Employee found successfully.");
            int Index = Main.H1.searchEmployee(A);
            JOptionPane.showMessageDialog(Main.P2, "\n----- Employee Statistics -----" + "\nName: " + Main.H1.getE1()[Index].getName() + "\nAddress: " + Main.H1.getE1()[Index].getAddress() + "\nPhone no: " + Main.H1.getE1()[Index].getPhoneNo() + "\nId: " + Main.H1.getE1()[Index].getId() + "\nSalary: " + Main.H1.getE1()[Index].getSalary() + "\nSalary paid: " + Main.H1.getE1()[Index].isSalaryPaid());
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "Sorry! No employee found.");
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        int A = Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter student id to search: "));
        if (Main.H1.isSearchStudent(A))
        {
            JOptionPane.showMessageDialog(Main.P2, "Student found successfully.");
            int Index = Main.H1.searchStudent(A);
            JOptionPane.showMessageDialog(Main.P2, "\n----- Student Statistics -----" + "\nName: " + Main.H1.getS1()[Index].getName() + "\nAddress: " + Main.H1.getS1()[Index].getAddress() + "\nPhone no: " + Main.H1.getS1()[Index].getPhoneNo() + "\nRoom no assigned: " + Main.H1.getS1()[Index].getRoomNoAssigned() + "\nStay months: " + Main.H1.getS1()[Index].getNoOfMonths() + "\nBill payed: " + Main.H1.getS1()[Index].isBillPayed() + "\nTotal bill: " + Main.H1.getS1()[Index].getTotalBillPerMonth() + "\nAdvance: " + Main.H1.getS1()[Index].getTotalAdvancePayed() + "\nBalance remaning: " + Main.H1.getS1()[Index].getTotalAmountPending());
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "Sorry! No student found.");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        int A = Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter student id for which you want to compute bill: "));
        if (Main.H1.isSearchStudent(A))
        {
            JOptionPane.showMessageDialog(Main.P2, "Billing record found successfully.");
            int Index = Main.H1.searchStudent(A);
            JOptionPane.showMessageDialog(Main.P2, "\n----- Student Statistics -----" + "\nName: " + Main.H1.getS1()[Index].getName() + "\nAddress: " + Main.H1.getS1()[Index].getAddress() + "\nPhone no: " + Main.H1.getS1()[Index].getPhoneNo() + "\nRoom no assigned: " + Main.H1.getS1()[Index].getRoomNoAssigned() + "\nStay months: " + Main.H1.getS1()[Index].getNoOfMonths() + "\n----- Billing Details -----" + "\nBill payed: " + Main.H1.getS1()[Index].isBillPayed() + "\nTotal bill: " + Main.H1.getS1()[Index].getTotalBillPerMonth() + "\nAdvance: " + Main.H1.getS1()[Index].getTotalAdvancePayed() + "\nBalance remaning: " + Main.H1.getS1()[Index].getTotalAmountPending());
        }
        else
        {
            JOptionPane.showMessageDialog(Main.P2, "Sorry! No billing record found.");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
            for (int i=0;i<Main.H1.getS1().length;i++)
            {
                Hostel.totalEarnings += Main.H1.getS1()[i].getTotalAmountPending();
            }
            JOptionPane.showMessageDialog(Main.P2, "Total monthly earnings: " + Hostel.totalEarnings);
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int A = Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter student id to delete: "));
        if (Main.H1.isSearchStudent(A))
        {
            int Index = Main.H1.searchStudent(A);
            JOptionPane.showMessageDialog(this, "Student found & deleted successfully!");
            for (int i=Index;i<Hostel.studentsCounter;i++)
            {
                Main.H1.getS1()[Index] = Main.H1.getS1()[Index+1];
            }
            Hostel.studentsCounter-=1;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Sorry, no student found!");          
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Main.H1.getS1()[Hostel.studentsCounter].setName(JOptionPane.showInputDialog(Main.P2, "Enter name of student: "));
        Main.H1.getS1()[Hostel.studentsCounter].setAddress(JOptionPane.showInputDialog(Main.P2, "Enter address of student: "));
        Main.H1.getS1()[Hostel.studentsCounter].setPhoneNo(JOptionPane.showInputDialog(Main.P2, "Enter phone no of student: "));
        Main.H1.getS1()[Hostel.studentsCounter].setNoOfMonths(Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter no. of months: ")));
        Main.H1.getS1()[Hostel.studentsCounter].setRoomNoAssigned(Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter room no. assigned: "))-1);
        Main.H1.getS1()[Hostel.studentsCounter].setTotalBillPerMonth(Main.H1.getR1()[Main.H1.getS1()[Hostel.studentsCounter].getRoomNoAssigned()].getCharges());
        Main.H1.getS1()[Hostel.studentsCounter].setTotalAdvancePayed(Double.parseDouble(JOptionPane.showInputDialog(this, "Enter total advance amount: ")));
        Main.H1.getS1()[Hostel.studentsCounter].setId(Hostel.studentsCounter+1);
        Hostel.studentsCounter++;
        JOptionPane.showMessageDialog(this, "New student added successfully.");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        int A = Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter student id to update: "));
        if (Main.H1.isSearchStudent(A))
        {
            int Index = Main.H1.searchStudent(A);
            JOptionPane.showMessageDialog(this, "Student found.");
            Main.H1.getS1()[Index].setAddress(JOptionPane.showInputDialog(Main.P2, "Enter address of student: "));
            Main.H1.getS1()[Index].setPhoneNo(JOptionPane.showInputDialog(Main.P2, "Enter phone no of student: "));
            Main.H1.getS1()[Index].setNoOfMonths(Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter no. of months: ")));            
            JOptionPane.showMessageDialog(this, "Student found & updated successfully!");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Sorry, no student found!");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        Main.H1.getE1()[Hostel.employeeCounter].setName(JOptionPane.showInputDialog(this, "Enter name of employee: "));
        Main.H1.getE1()[Hostel.employeeCounter].setAddress(JOptionPane.showInputDialog(this, "Enter address of employee: "));
        Main.H1.getE1()[Hostel.employeeCounter].setPhoneNo(JOptionPane.showInputDialog(this, "Enter phone no. of employee: "));
        Main.H1.getE1()[Hostel.employeeCounter].setSalary(Double.parseDouble(JOptionPane.showInputDialog(this, "Emter salary for employee: ")));
        Main.H1.getE1()[Hostel.employeeCounter].setId(Hostel.employeeCounter+1);
        Hostel.employeeCounter++;
        JOptionPane.showMessageDialog(this, "New employee added successfully.");
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        int A = Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter employee id to delete: "));
        if (Main.H1.isSearchEmployee(A))
        {
            int Index = Main.H1.searchEmployee(A);
            JOptionPane.showMessageDialog(this, "Employee found & deleted successfully!");
            for (int i=0;i<Hostel.employeeCounter;i++)
            {
                Main.H1.getE1()[i] = Main.H1.getE1()[i+1];
            }
            Hostel.employeeCounter-=1;
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Sorry, no employee found!");          
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int A = Integer.parseInt(JOptionPane.showInputDialog(Main.P2, "Enter employee id to update: "));
        if (Main.H1.isSearchEmployee(A))
        {
            int Index = Main.H1.searchEmployee(A);
            Main.H1.getE1()[Index].setAddress(JOptionPane.showInputDialog(this, "Enter address to update: "));
            Main.H1.getE1()[Index].setSalary(Double.parseDouble(JOptionPane.showInputDialog(this, "Enter salary to update: ")));
            Main.H1.getE1()[Index].setSalaryPaid(Boolean.valueOf(JOptionPane.showInputDialog(this, "Enter salary status i-e true or false: ")));
            JOptionPane.showMessageDialog(this, "Employee found & updates successfully!");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Sorry, no employee found!");       
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PageTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PageTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PageTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PageTwo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PageTwo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
